export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const CHANGE_THEME = "CHANGE_THEME";
export const DISABLED_BUTTONS = "DISABLED_BUTTONS";
export const ENABLE_BUTTONS = "ENABLE_BUTTONS";
